//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eleven.VS.Templates.Ado.Dsl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TypeConverters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TypeConverters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eleven.VS.Templates.Ado.Dsl.Resources.TypeConverters", typeof(TypeConverters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.HashSet&lt;T&gt;.
        /// </summary>
        public static string CollectionType_HashSet {
            get {
                return ResourceManager.GetString("CollectionType_HashSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal.
        /// </summary>
        public static string DomainEntity_AccessModifier_internal {
            get {
                return ResourceManager.GetString("DomainEntity_AccessModifier_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        public static string DomainEntity_AccessModifier_private {
            get {
                return ResourceManager.GetString("DomainEntity_AccessModifier_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected.
        /// </summary>
        public static string DomainEntity_AccessModifier_protected {
            get {
                return ResourceManager.GetString("DomainEntity_AccessModifier_protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected internal.
        /// </summary>
        public static string DomainEntity_AccessModifier_protected_internal {
            get {
                return ResourceManager.GetString("DomainEntity_AccessModifier_protected_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        public static string DomainEntity_AccessModifier_public {
            get {
                return ResourceManager.GetString("DomainEntity_AccessModifier_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal.
        /// </summary>
        public static string DomainEntityCollection_AccessModifier_internal {
            get {
                return ResourceManager.GetString("DomainEntityCollection_AccessModifier_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        public static string DomainEntityCollection_AccessModifier_private {
            get {
                return ResourceManager.GetString("DomainEntityCollection_AccessModifier_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected.
        /// </summary>
        public static string DomainEntityCollection_AccessModifier_protected {
            get {
                return ResourceManager.GetString("DomainEntityCollection_AccessModifier_protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected internal.
        /// </summary>
        public static string DomainEntityCollection_AccessModifier_protected_internal {
            get {
                return ResourceManager.GetString("DomainEntityCollection_AccessModifier_protected_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        public static string DomainEntityCollection_AccessModifier_public {
            get {
                return ResourceManager.GetString("DomainEntityCollection_AccessModifier_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.Dictionary&lt;string, T&gt;.
        /// </summary>
        public static string DomainEntityCollection_CollectionType_Dictionary {
            get {
                return ResourceManager.GetString("DomainEntityCollection_CollectionType_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.ICollection&lt;T&gt;.
        /// </summary>
        public static string DomainEntityCollection_CollectionType_ICollection {
            get {
                return ResourceManager.GetString("DomainEntityCollection_CollectionType_ICollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.List&lt;T&gt;.
        /// </summary>
        public static string DomainEntityCollection_CollectionType_List {
            get {
                return ResourceManager.GetString("DomainEntityCollection_CollectionType_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal.
        /// </summary>
        public static string DomainEntityProperty_AccessModifier_internal {
            get {
                return ResourceManager.GetString("DomainEntityProperty_AccessModifier_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        public static string DomainEntityProperty_AccessModifier_private {
            get {
                return ResourceManager.GetString("DomainEntityProperty_AccessModifier_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected.
        /// </summary>
        public static string DomainEntityProperty_AccessModifier_protected {
            get {
                return ResourceManager.GetString("DomainEntityProperty_AccessModifier_protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        public static string DomainEntityProperty_AccessModifier_public {
            get {
                return ResourceManager.GetString("DomainEntityProperty_AccessModifier_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.Dictionary&lt;string, T&gt;.
        /// </summary>
        public static string DomainEntityProperty_CollectionType_Dictionary {
            get {
                return ResourceManager.GetString("DomainEntityProperty_CollectionType_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.ICollection&lt;T&gt;.
        /// </summary>
        public static string DomainEntityProperty_CollectionType_ICollection {
            get {
                return ResourceManager.GetString("DomainEntityProperty_CollectionType_ICollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.List&lt;T&gt;.
        /// </summary>
        public static string DomainEntityProperty_CollectionType_List {
            get {
                return ResourceManager.GetString("DomainEntityProperty_CollectionType_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string DomainEntityProperty_CollectionType_None {
            get {
                return ResourceManager.GetString("DomainEntityProperty_CollectionType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal.
        /// </summary>
        public static string DomainPrimitiveProperty_AccessModifier_internal {
            get {
                return ResourceManager.GetString("DomainPrimitiveProperty_AccessModifier_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        public static string DomainPrimitiveProperty_AccessModifier_private {
            get {
                return ResourceManager.GetString("DomainPrimitiveProperty_AccessModifier_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected.
        /// </summary>
        public static string DomainPrimitiveProperty_AccessModifier_protected {
            get {
                return ResourceManager.GetString("DomainPrimitiveProperty_AccessModifier_protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        public static string DomainPrimitiveProperty_AccessModifier_public {
            get {
                return ResourceManager.GetString("DomainPrimitiveProperty_AccessModifier_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.Dictionary&lt;string, T&gt;.
        /// </summary>
        public static string DomainPrimitiveProperty_CollectionType_Dictionary {
            get {
                return ResourceManager.GetString("DomainPrimitiveProperty_CollectionType_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.ICollection&lt;T&gt;.
        /// </summary>
        public static string DomainPrimitiveProperty_CollectionType_ICollection {
            get {
                return ResourceManager.GetString("DomainPrimitiveProperty_CollectionType_ICollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.List&lt;T&gt;.
        /// </summary>
        public static string DomainPrimitiveProperty_CollectionType_List {
            get {
                return ResourceManager.GetString("DomainPrimitiveProperty_CollectionType_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string DomainPrimitiveProperty_CollectionType_None {
            get {
                return ResourceManager.GetString("DomainPrimitiveProperty_CollectionType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Boolean.
        /// </summary>
        public static string PrimitivePropertySystemType_Boolean {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Byte.
        /// </summary>
        public static string PrimitivePropertySystemType_Byte {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Char.
        /// </summary>
        public static string PrimitivePropertySystemType_Char {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.DateTime.
        /// </summary>
        public static string PrimitivePropertySystemType_DateTime {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Decimal.
        /// </summary>
        public static string PrimitivePropertySystemType_Decimal {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double.
        /// </summary>
        public static string PrimitivePropertySystemType_Double {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Guid.
        /// </summary>
        public static string PrimitivePropertySystemType_Guid {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Int16.
        /// </summary>
        public static string PrimitivePropertySystemType_Int16 {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Int16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Int32.
        /// </summary>
        public static string PrimitivePropertySystemType_Int32 {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Int64.
        /// </summary>
        public static string PrimitivePropertySystemType_Int64 {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.SByte.
        /// </summary>
        public static string PrimitivePropertySystemType_SByte {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_SByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Single.
        /// </summary>
        public static string PrimitivePropertySystemType_Single {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String.
        /// </summary>
        public static string PrimitivePropertySystemType_String {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.UInt16.
        /// </summary>
        public static string PrimitivePropertySystemType_UInt16 {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_UInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.UInt32.
        /// </summary>
        public static string PrimitivePropertySystemType_UInt32 {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_UInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.UInt64.
        /// </summary>
        public static string PrimitivePropertySystemType_UInt64 {
            get {
                return ResourceManager.GetString("PrimitivePropertySystemType_UInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool.
        /// </summary>
        public static string PrimitivePropertyType_Bool {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        public static string PrimitivePropertyType_Byte {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char.
        /// </summary>
        public static string PrimitivePropertyType_Char {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.DateTime.
        /// </summary>
        public static string PrimitivePropertyType_DateTime {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimal.
        /// </summary>
        public static string PrimitivePropertyType_Decimal {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double.
        /// </summary>
        public static string PrimitivePropertyType_Double {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float.
        /// </summary>
        public static string PrimitivePropertyType_Float {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Guid.
        /// </summary>
        public static string PrimitivePropertyType_Guid {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int.
        /// </summary>
        public static string PrimitivePropertyType_Int {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long.
        /// </summary>
        public static string PrimitivePropertyType_Long {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sbyte.
        /// </summary>
        public static string PrimitivePropertyType_SByte {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_SByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short.
        /// </summary>
        public static string PrimitivePropertyType_Short {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        public static string PrimitivePropertyType_String {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint.
        /// </summary>
        public static string PrimitivePropertyType_UInt {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_UInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ulong.
        /// </summary>
        public static string PrimitivePropertyType_ULong {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_ULong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ushort.
        /// </summary>
        public static string PrimitivePropertyType_UShort {
            get {
                return ResourceManager.GetString("PrimitivePropertyType_UShort", resourceCulture);
            }
        }
    }
}
