// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Eleven.VS.Templates.Ado.Package.CustomCode.TextTemplates.Domain
{
    using Eleven.VS.Templates.Ado.Package.TextTemplates.Helper;
    using Eleven.VS.Templates.Ado.Dsl.Resources;
    using Eleven.VS.Templates.Ado.Dsl.Util;
    using Eleven.VS.Templates.Ado.Dsl;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class CodeGeneratorDomainEntity : Eleven.VS.Templates.Ado.Dsl.Util.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 10 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DomainEntity.DomainEntityModel.ProjectImplementationEntity));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 12 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"

	PushIndent("    ");

            
            #line default
            #line hidden
            
            #line 15 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.AccessModifier));
            
            #line default
            #line hidden
            this.Write(" partial class ");
            
            #line 15 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 17 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"

	PushIndent("    ");
	if(TemplateHelperDomainEntity.hasEntityCollectionsGenerated(DomainEntity))
	{

            
            #line default
            #line hidden
            this.Write("public ");
            
            #line 22 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n{\r\n");
            
            #line 24 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"

		PushIndent("    ");
		foreach (DomainEntityProperty domainEntityProperty in DomainEntity.DomainEntityProperties)
		{
			if (domainEntityProperty.IsGeneratedCollection && domainEntityProperty.CollectionType == TypeConverters.DomainEntityProperty_CollectionType_ICollection)
			{

            
            #line default
            #line hidden
            
            #line 31 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainEntityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = new System.Collections.Generic.HashSet<");
            
            #line 31 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainEntityProperty.DomainEntityType));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n");
            
            #line 33 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"

			}
		}
		PopIndent();

            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            
            #line 40 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"

	}
	foreach (DomainEntityProperty domainEntityProperty in DomainEntity.DomainEntityProperties)
	{

            
            #line default
            #line hidden
            
            #line 45 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainEntityProperty.AccessModifier));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 45 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperCommon.Get_StringType(domainEntityProperty)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 45 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainEntityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\r\n");
            
            #line 47 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"

	}

            
            #line default
            #line hidden
            
            #line 50 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"

	foreach (PrimitiveProperty primitiveProperty in DomainEntity.PrimitiveProperties)
	{

            
            #line default
            #line hidden
            
            #line 54 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primitiveProperty.AccessModifier));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 54 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperCommon.Get_StringType(primitiveProperty)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 54 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primitiveProperty.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\r\n");
            
            #line 56 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"

	}
	PopIndent();

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 61 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Domain\CodeGeneratorDomainEntity.tt"

	PopIndent();

            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
