// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Eleven.VS.Templates.Ado.Package.CustomCode.TextTemplates.Database
{
    using Eleven.VS.Templates.Ado.Package.TextTemplates.Helper;
    using Eleven.VS.Templates.Ado.Dsl.Util;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class CodeGeneratorDatabaseSPInsert : Eleven.VS.Templates.Ado.Dsl.Util.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("CREATE PROCEDURE ");
            
            #line 8 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Insert_SPName(DomainEntity)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 9 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 10 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Parameters_StoreProcedure(DomainEntity, 0, true, true, true)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 11 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("AS\r\nBEGIN\r\n");
            
            #line 14 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            this.Write("SET NOCOUNT ON\r\n\r\nINSERT INTO ");
            
            #line 17 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_TableName(DomainEntity)));
            
            #line default
            #line hidden
            this.Write(" (\r\n");
            
            #line 18 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 19 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Columns_StoreProcedure(DomainEntity, 0, false, true)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 20 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write(")\r\nVALUES (\r\n");
            
            #line 23 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 24 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_ColumnParameters_StoreProcedure(DomainEntity, 0, false, true)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 25 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 27 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"

if(TemplateHelperDatabase.DomainEntity_Has_OutputParameters(DomainEntity))
{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 32 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_OutputKey(DomainEntity, 0)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 33 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\nSET NOCOUNT OFF\r\n");
            
            #line 38 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPInsert.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("END");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
