// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Eleven.VS.Templates.Ado.Package.CustomCode.TextTemplates.Database
{
    using Eleven.VS.Templates.Ado.Package.TextTemplates.Helper;
    using Eleven.VS.Templates.Ado.Dsl.Util;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class CodeGeneratorDatabaseSPSelect : Eleven.VS.Templates.Ado.Dsl.Util.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("CREATE PROCEDURE ");
            
            #line 8 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Select_SPName(DomainEntity)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 9 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 10 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Parameters_StoreProcedure(DomainEntity, 0, true, true)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 11 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("AS\r\nBEGIN\r\n");
            
            #line 14 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            this.Write("SET NOCOUNT ON\r\n\r\nSELECT\r\n");
            
            #line 18 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 19 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Columns_StoreProcedure(DomainEntity, 0, true, true)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 20 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("FROM ");
            
            #line 21 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_TableName(DomainEntity)));
            
            #line default
            #line hidden
            this.Write("\r\n-- Put your filters here... --\r\n/*\r\nWHERE\r\n");
            
            #line 25 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 26 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_ColumnParameters_Where_StoreProcedure(DomainEntity, 0, true, true)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 27 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("*/\r\n\r\nSET NOCOUNT OFF\r\n");
            
            #line 31 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\Database\CodeGeneratorDatabaseSPSelect.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("END");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
