//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eleven.VS.Templates.Ado.Dsl
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "elevenentitymodel";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Eleven Entity Model";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Eleven";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ElevenEntityModelDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ElevenEntityModelCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ElevenEntityModelExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ElevenEntityModelCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewElevenEntityModelExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ElevenEntityModelCommandSetId), 0x0001);
	
		// Package identifier
		public const string ElevenEntityModelPackageId = "1fd0aa89-51da-4597-8e90-29b3e14673d2";
		
		// Editor factory identifier
		public const string ElevenEntityModelEditorFactoryId = "d0f144bd-1aac-4163-8875-48f048a358c3";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string ElevenEntityModelModelExplorerToolWindowId = "7be6c107-ae92-4e8a-9537-618e4186d78c";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Eleven.VS.Templates.Ado.Dsl
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ElevenEntityModelCommandSetId = "d7203678-101c-4c12-8e9d-01ab6fb961f6";
	}
}