// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Eleven.VS.Templates.Ado.Package.CustomCode.TextTemplates.DataAccess
{
    using Eleven.VS.Templates.Ado.Package.TextTemplates.Helper;
    using Eleven.VS.Templates.Ado.Dsl.Util;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class CodeGeneratorDataAccessClass : Eleven.VS.Templates.Ado.Dsl.Util.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 8 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"

String EntityName = TemplateHelperDataAccess.Get_Variable_Name(DomainEntity.Name);
String DomainEntityCollectionName = String.Empty;

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Data;\r\nusing System.Data.Common;\r\nusing Microsoft.Pra" +
                    "ctices.EnterpriseLibrary.Data;\r\nusing ");
            
            #line 16 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DomainEntity.DomainEntityModel.ProjectImplementationDataAccessCore));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 17 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DomainEntity.DomainEntityModel.ProjectImplementationEntity));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 19 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DomainEntity.DomainEntityModel.ProjectImplementationDataAccess));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 21 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 22 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.AccessModifier));
            
            #line default
            #line hidden
            this.Write(" partial class ");
            
            #line 22 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_DataAccess_Class_Name(DomainEntity)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 24 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            this.Write("private static DatabaseProviderFactory oDatabaseProviderFactory = new DatabasePro" +
                    "viderFactory();\r\nprivate Database oDatabase = oDatabaseProviderFactory.Create(Co" +
                    "nexion.cnConexion);\r\n\r\n//*********************** FUNCION PARA REGISTRO DE ");
            
            #line 28 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name.ToUpper()));
            
            #line default
            #line hidden
            this.Write(" ***********************//\r\npublic ");
            
            #line 29 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 29 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_DataAccess_Insert_MethodName(DomainEntity)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 29 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 29 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n");
            
            #line 31 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            this.Write("DbCommand oDbCommand = oDatabase.GetStoredProcCommand(Procedimiento.");
            
            #line 32 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Insert_SPName_Constant(DomainEntity)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 34 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Parameter_Text(DomainEntity, false, false, false, 0)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\noDatabase.ExecuteNonQuery(oDbCommand);\r\n");
            
            #line 37 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"

if(TemplateHelperDataAccess.DomainEntity_Has_OutputParameters(DomainEntity))
{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 42 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Output_Parameters(DomainEntity, 3)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\nreturn ");
            
            #line 47 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 48 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n//******************** FUNCION PARA ACTUALIZACION DE ");
            
            #line 51 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name.ToUpper()));
            
            #line default
            #line hidden
            this.Write(" *********************//\r\npublic ");
            
            #line 52 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 52 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_DataAccess_Update_MethodName(DomainEntity)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 52 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 52 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n");
            
            #line 54 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            this.Write("DbCommand oDbCommand = oDatabase.GetStoredProcCommand(Procedimiento.");
            
            #line 55 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Update_SPName_Constant(DomainEntity)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 57 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Parameter_Text(DomainEntity, false, false, true, 0)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\noDatabase.ExecuteNonQuery(oDbCommand);\r\n\r\nreturn ");
            
            #line 61 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 62 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n//********************* FUNCION PARA ELIMINACION DE ");
            
            #line 65 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name.ToUpper()));
            
            #line default
            #line hidden
            this.Write(" **********************//\r\npublic ");
            
            #line 66 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 66 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_DataAccess_Delete_MethodName(DomainEntity)));
            
            #line default
            #line hidden
            this.Write("(\r\n");
            
            #line 67 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 68 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Method_Key_Parameters(DomainEntity, 3)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 69 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n");
            
            #line 72 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 73 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 73 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 73 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\nDbCommand oDbCommand = oDatabase.GetStoredProcCommand(Procedimiento.");
            
            #line 75 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Delete_SPName_Constant(DomainEntity)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 76 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Parameter_Text(DomainEntity, true, true, true, 0)));
            
            #line default
            #line hidden
            this.Write("\r\noDatabase.ExecuteNonQuery(oDbCommand);\r\n\r\nreturn ");
            
            #line 79 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 80 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n//******************* FUNCION PARA SELECCION POR ID DE ");
            
            #line 83 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name.ToUpper()));
            
            #line default
            #line hidden
            this.Write(" *******************//\r\npublic ");
            
            #line 84 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 84 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_DataAccess_SelectId_MethodName(DomainEntity)));
            
            #line default
            #line hidden
            this.Write("(\r\n");
            
            #line 85 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 86 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Method_Key_Parameters(DomainEntity, 3)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 87 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n");
            
            #line 90 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 91 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 91 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 91 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write("();\r\nDbCommand oDbCommand = oDatabase.GetStoredProcCommand(Procedimiento.");
            
            #line 92 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_SelectId_SPName_Constant(DomainEntity)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 94 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Parameter_Text(DomainEntity, true, true, true, 0)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nusing (IDataReader oIDataReader = oDatabase.ExecuteReader(oDbCommand))\r\n{\r\n");
            
            #line 98 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            this.Write("while (oIDataReader.Read())\r\n{\r\n");
            
            #line 101 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 102 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Mapping_Text(DomainEntity, String.Empty, 0)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 103 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 105 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\nreturn ");
            
            #line 108 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 109 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n//********************** FUNCION PARA SELECCION DE ");
            
            #line 112 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name.ToUpper()));
            
            #line default
            #line hidden
            this.Write(" ***********************//\r\n");
            
            #line 113 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"

DomainEntityCollectionName = TemplateHelperDataAccess.DomainEntity_Has_DomainEntityCollections(DomainEntity);
if(String.IsNullOrEmpty(DomainEntityCollectionName))
	DomainEntityCollectionName = String.Concat("System.Collections.Generic.List<", DomainEntity.Name, ">");

            
            #line default
            #line hidden
            this.Write("public ");
            
            #line 118 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityCollectionName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 118 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_DataAccess_Select_MethodName(DomainEntity)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 118 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 118 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n");
            
            #line 120 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"

EntityName = TemplateHelperDataAccess.Get_Variable_Name(String.Concat("Lista", DomainEntity.Name));
PushIndent("    ");

            
            #line default
            #line hidden
            
            #line 124 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityCollectionName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 124 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 124 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityCollectionName));
            
            #line default
            #line hidden
            this.Write("();\r\nDbCommand oDbCommand = oDatabase.GetStoredProcCommand(Procedimiento.");
            
            #line 125 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Select_SPName_Constant(DomainEntity)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 127 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Parameter_Text(DomainEntity, false, false, true, 0)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nusing (IDataReader oIDataReader = oDatabase.ExecuteReader(oDbCommand))\r\n{\r\n");
            
            #line 131 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            this.Write("while (oIDataReader.Read())\r\n{\r\n");
            
            #line 134 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 135 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDataAccess.Get_Mapping_Text(DomainEntity, EntityName, 0)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 136 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 138 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\nreturn ");
            
            #line 141 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 142 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            
            #line 145 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 147 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 149 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\DataAccess\CodeGeneratorDataAccessClass.tt"

ClearIndent();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
