// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Eleven.VS.Templates.Ado.Package.CustomCode.TextTemplates.CrossCutting
{
    using Eleven.VS.Templates.Ado.Package.TextTemplates.Helper;
    using Eleven.VS.Templates.Ado.Dsl.Util;
    using Eleven.VS.Templates.Ado.Dsl;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class CodeGeneratorCrossCuttingProcedures : Eleven.VS.Templates.Ado.Dsl.Util.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 9 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DomainEntityModel.ProjectImplementationDataAccessCore));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 11 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            this.Write("public class Procedimiento\r\n{\r\n\r\n");
            
            #line 15 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
 PushIndent("    "); 
            
            #line default
            #line hidden
            
            #line 16 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"

foreach(DomainEntity domainEntity in this.DomainEntityModel.DomainEntities)
{

            
            #line default
            #line hidden
            this.Write("#region PROCEDIMIENTOS ALMACENADOS ");
            
            #line 20 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainEntity.Name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("\r\npublic const string ");
            
            #line 21 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperCrossCutting.Get_Insert_SPName_Constant(domainEntity)));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 21 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Insert_SPName(domainEntity)));
            
            #line default
            #line hidden
            this.Write("\";\r\npublic const string ");
            
            #line 22 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperCrossCutting.Get_Update_SPName_Constant(domainEntity)));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 22 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Update_SPName(domainEntity)));
            
            #line default
            #line hidden
            this.Write("\";\r\npublic const string ");
            
            #line 23 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperCrossCutting.Get_Delete_SPName_Constant(domainEntity)));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 23 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Delete_SPName(domainEntity)));
            
            #line default
            #line hidden
            this.Write("\";\r\npublic const string ");
            
            #line 24 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperCrossCutting.Get_SelectId_SPName_Constant(domainEntity)));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 24 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_SelectId_SPName(domainEntity)));
            
            #line default
            #line hidden
            this.Write("\";\r\npublic const string ");
            
            #line 25 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperCrossCutting.Get_Select_SPName_Constant(domainEntity)));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 25 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelperDatabase.Get_DataAccess_Select_SPName(domainEntity)));
            
            #line default
            #line hidden
            this.Write("\";\r\n#endregion\r\n\r\n");
            
            #line 28 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"

}

            
            #line default
            #line hidden
            
            #line 31 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 33 "D:\Projects\Eleven.VS.Templates.Ado\Eleven.VS.Templates.Ado.Package\CustomCode\TextTemplates\CrossCutting\CodeGeneratorCrossCuttingProcedures.tt"
 PopIndent(); 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
