//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eleven.VS.Templates.Ado.Wizard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SolutionTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SolutionTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eleven.VS.Templates.Ado.Wizard.Resources.SolutionTemplate", typeof(SolutionTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 Modeling and Design.
        /// </summary>
        public static string A_SolutionFolder_Modeling {
            get {
                return ResourceManager.GetString("A_SolutionFolder_Modeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Layers.
        /// </summary>
        public static string B_SolutionFolder_Layers {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1 Presentation.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_1_Mobile {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_1_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_1_Mobile_1_Android {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_1_Mobile_1_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Phone.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_1_Mobile_2_WindowsPhone {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_1_Mobile_2_WindowsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIA.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_2_RIA {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_2_RIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight Client.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_2_RIA_1_SilverlightClient {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_2_RIA_1_SilverlightClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight Mobile.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_2_RIA_2_SilverlightMobile {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_2_RIA_2_SilverlightMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_3_Web {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_3_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP .NET Cient.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_3_Web_1_ASPNETCient {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_3_Web_1_ASPNETCient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP .NET MVC Cient.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_3_Web_2_ASPNETMVCCient {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_3_Web_2_ASPNETMVCCient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_4_Windows {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_4_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBA Client.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_4_Windows_1_OBAClient {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_4_Windows_1_OBAClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinForm Client.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_4_Windows_2_WinFormClient {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_4_Windows_2_WinFormClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF Client.
        /// </summary>
        public static string B_SolutionFolder_Layers_1_Presentation_4_Windows_3_WPFClient {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_1_Presentation_4_Windows_3_WPFClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2 Distributed Services.
        /// </summary>
        public static string B_SolutionFolder_Layers_2_DistributedServices {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_2_DistributedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.1 Core.
        /// </summary>
        public static string B_SolutionFolder_Layers_2_DistributedServices_1_Core {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_2_DistributedServices_1_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.2 MainModule.
        /// </summary>
        public static string B_SolutionFolder_Layers_2_DistributedServices_2_MainModule {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_2_DistributedServices_2_MainModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.3 Deployment.
        /// </summary>
        public static string B_SolutionFolder_Layers_2_DistributedServices_3_Deployment {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_2_DistributedServices_3_Deployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3 Application.
        /// </summary>
        public static string B_SolutionFolder_Layers_3_Application {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_3_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.1 Core.
        /// </summary>
        public static string B_SolutionFolder_Layers_3_Application_1_Core {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_3_Application_1_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.2 MainModule.
        /// </summary>
        public static string B_SolutionFolder_Layers_3_Application_2_MainModule {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_3_Application_2_MainModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4 Domain.
        /// </summary>
        public static string B_SolutionFolder_Layers_4_Domain {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_4_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.1 Core.
        /// </summary>
        public static string B_SolutionFolder_Layers_4_Domain_1_Core {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_4_Domain_1_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.2 MainModule.
        /// </summary>
        public static string B_SolutionFolder_Layers_4_Domain_2_MainModule {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_4_Domain_2_MainModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5 Infraestructure.
        /// </summary>
        public static string B_SolutionFolder_Layers_5_Infraestructure {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_5_Infraestructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.1 Data.
        /// </summary>
        public static string B_SolutionFolder_Layers_5_Infraestructure_1_Data {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_5_Infraestructure_1_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.2 Cross Cutting.
        /// </summary>
        public static string B_SolutionFolder_Layers_5_Infraestructure_2_CrossCutting {
            get {
                return ResourceManager.GetString("B_SolutionFolder_Layers_5_Infraestructure_2_CrossCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Database.
        /// </summary>
        public static string C_SolutionFolder_Database {
            get {
                return ResourceManager.GetString("C_SolutionFolder_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Solution Items.
        /// </summary>
        public static string D_SolutionFolder_SolutionItems {
            get {
                return ResourceManager.GetString("D_SolutionFolder_SolutionItems", resourceCulture);
            }
        }
    }
}
